spring:
  datasource:
    url: jdbc:mysql://47.103.60.221:3306/Aurora_new
    username: root
    password: Xue85869877.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  web:
    resources:
      static-locations: "classpath:/static"

  servlet:
    multipart:
      max-file-size: 13MB
      max-request-size: 13MB

  output:
    ansi:
      enabled: always

#端口号
server:
  port: 8088
  servlet:
    context-path: /Aurora

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#logging:
  #file:
    #name: /myspringboot/log/my.log

my:
  uploadImgUrl: http://www.shanshaoxy.cn:8089/AuroraApp/Resource/Photo
  uploadFileUrl: http://www.shanshaoxy.cn:8089/AuroraApp/Resource/File
  uploadImgPath: /usr/resources/AuroraApp/Resource/Photo/
  uploadFilePath: /usr/resources/AuroraApp/Resource/File/
  #uploadImgPath: D://Programs/Self/Aurora/save/Photo/
  #uploadFilePath: D://Programs/Self/Aurora/save/File/